<a href="https://colab.research.google.com/github/Usman972002/Python/blob/main/ML/NumPyMl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

--> **NumPy** is a Python library used for working with arrays.
-->NumPy stands for Numerical Python.

Why Use NumPy?
-->In Python we have lists that serve the purpose of arrays, but they are slow to process.

-->NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

-->The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


In [3]:
arr = np.array([[1,2,3],[4,5,6]]) #creating an array using numpy
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
print(type(arr)) #Checking the type of array
print(arr.dtype) #tells the datatype of the array
print(arr.ndim) # prints the number of dimensions of the array

<class 'numpy.ndarray'>
int64
2


Higher Dimensional Arrays::
-------------------------------------
--> An array can have any number of dimensions.
-->When the array is created, you can define the number of dimensions by using the ndmin argument

In [11]:
arr1 = np.array([1,2,3,4,5],ndmin=5) #creating 5 dimensional array
print(arr1)
print(arr1.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [16]:
# Accesing array elements
print(arr[0,1]) 
print(arr[-2,-1])#Negative indexing

2
3


In [18]:
arr2 = np.array([i for i in range(10)])
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
# Slicing array elements
print(arr2[1:5])
print(arr2[-3:-1]) #Negative Slicing
print(arr[0,0:2])# 2D Slicing
print(arr2[1:10:2])#Step Slicing

[1 2 3 4]
[7 8]
[1 2]
[1 3 5 7 9]


Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character.

i - integer,
b - boolean,
u - unsigned integer,
f - float,
c - complex float,
m - timedelta,
M - datetime,
O - object,
S - string,
U - unicode string,
V - fixed chunk of memory for other type ( void )

In [25]:
arr3 = np.array([1,2,3,4,5,6,6,677,8],dtype='f') #creating our own data type for the array
print(arr3.dtype)

float32


Converting Data Type on Existing Arrays

-->The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

-->The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [31]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr4.dtype)
# Converting the above existing array data type to another data type
arr5 = arr4.astype('S') #Converted it to String
print(arr5.dtype)
arr5

int64
|S21


array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10'],
      dtype='|S21')

In [32]:
# The shape of an array is the number of elements in each dimension
arr1.shape

(1, 1, 1, 1, 5)

In [45]:
# Reshaping means changing the shape of an array.
# By reshaping we can add or remove dimensions or change number of elements in each dimension.
arr6 = np.ones(9)
print(arr6)
arr7 = arr6.reshape(3,3)
print(arr7)
arr7.ndim

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2

In [48]:
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
arr8 = np.zeros((3,3,3))
print(arr8)
arr9 = arr8.reshape(-1)
print(arr9)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [5]:
# The function nditer() is a helping function that can be used from very basic to very advanced iterations
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in a: #Normal iteration
  print(i)
for i in np.nditer(a):#prints Scalar values in the given matrix
  print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [10]:
# Array Joining
u = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((u,b))) #simply adding two arrays
print(np.stack((u,b),axis=1)) # stack using arrays
print(np.hstack((u,b))) # stack along Rows
print(np.vstack((u,b))) # stack along Coloumns
print(np.dstack((u,b))) # stack along depth


[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [16]:
# Splitting Data
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(array, 3)
print(newarr)
print(np.hsplit(array,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [19]:
# Searching and Sorting Arrays
# To search an array, use the where() method
# The NumPy ndarray object has a function called sort(), that will sort a specified array.
a = np.array([1, 2, 3, 4, 5, 4, 4])

print(np.where(a == 4))
print(np.sort(a))

(array([3, 5, 6]),)
[1 2 3 4 4 4 5]
