<a href="https://colab.research.google.com/github/Usman972002/Python/blob/main/ML/NumPyMl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

--> **NumPy** is a Python library used for working with arrays.
-->NumPy stands for Numerical Python.

Why Use NumPy?
-->In Python we have lists that serve the purpose of arrays, but they are slow to process.

-->NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

-->The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


In [ ]:
arr = np.array([[1,2,3],[4,5,6]]) #creating an array using numpy
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(arr)) #Checking the type of array
print(arr.dtype) #tells the datatype of the array
print(arr.ndim) # prints the number of dimensions of the array

<class 'numpy.ndarray'>
int64
2


Higher Dimensional Arrays::
-------------------------------------
--> An array can have any number of dimensions.
-->When the array is created, you can define the number of dimensions by using the ndmin argument

In [ ]:
arr1 = np.array([1,2,3,4,5],ndmin=5) #creating 5 dimensional array
print(arr1)
print(arr1.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [ ]:
# Accesing array elements
print(arr[0,1]) 
print(arr[-2,-1])#Negative indexing

2
3


In [ ]:
arr2 = np.array([i for i in range(10)])
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Slicing array elements
print(arr2[1:5])
print(arr2[-3:-1]) #Negative Slicing
print(arr[0,0:2])# 2D Slicing
print(arr2[1:10:2])#Step Slicing

[1 2 3 4]
[7 8]
[1 2]
[1 3 5 7 9]


Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character.

i - integer,
b - boolean,
u - unsigned integer,
f - float,
c - complex float,
m - timedelta,
M - datetime,
O - object,
S - string,
U - unicode string,
V - fixed chunk of memory for other type ( void )

In [ ]:
arr3 = np.array([1,2,3,4,5,6,6,677,8],dtype='f') #creating our own data type for the array
print(arr3.dtype)

float32


Converting Data Type on Existing Arrays

-->The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

-->The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr4.dtype)
# Converting the above existing array data type to another data type
arr5 = arr4.astype('S') #Converted it to String
print(arr5.dtype)
arr5

int64
|S21


array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10'],
      dtype='|S21')

In [ ]:
# The shape of an array is the number of elements in each dimension
arr1.shape

(1, 1, 1, 1, 5)

In [ ]:
# Reshaping means changing the shape of an array.
# By reshaping we can add or remove dimensions or change number of elements in each dimension.
arr6 = np.ones(9)
print(arr6)
arr7 = arr6.reshape(3,3)
print(arr7)
arr7.ndim

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2

In [ ]:
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
arr8 = np.zeros((3,3,3))
print(arr8)
arr9 = arr8.reshape(-1)
print(arr9)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [ ]:
# The function nditer() is a helping function that can be used from very basic to very advanced iterations
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in a: #Normal iteration
  print(i)
for i in np.nditer(a):#prints Scalar values in the given matrix
  print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [ ]:
# Array Joining
u = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((u,b))) #simply adding two arrays
print(np.stack((u,b),axis=1)) # stack using arrays
print(np.hstack((u,b))) # stack along Rows
print(np.vstack((u,b))) # stack along Coloumns
print(np.dstack((u,b))) # stack along depth


[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# Splitting Data
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(array, 3)
print(newarr)
print(np.hsplit(array,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
# Searching and Sorting Arrays
# To search an array, use the where() method
# The NumPy ndarray object has a function called sort(), that will sort a specified array.
a = np.array([1, 2, 3, 4, 5, 4, 4])

print(np.where(a == 4))
print(np.sort(a))

(array([3, 5, 6]),)
[1 2 3 4 4 4 5]


Random numbers in NumPy

-->Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

-->NumPy offers the random module to work with random numbers.


In [4]:
from numpy import random as r #importing random module from Numpy

In [8]:
x = r.randint(1000,10000) #Printing a random integer value from the range
print(x)
y = r.rand() # rand() method returns a float between 0 and 1
print(y)

1746
0.08631924486277398


In [13]:
# Arrays using random module
a = r.randint(100,size=(10)) #1-D array of size 10
print(a)
b = r.randint(1000,size=(3,5)) #2-D array of size 3rows and 5 columns
print(b)
c = r.rand(5) #1-D floating array with size 5
d = r.rand(3,5) #2-D floating array with 3 rows and 5 coloumns
print(c)
print(d)
# The choice() method takes an array as a parameter and randomly returns one of the values.
e = r.choice([1,2,3,4,5,6])
print(e)
# The choice() method also allows you to return an array of values.
# Add a size parameter to specify the shape of the array.
f = r.choice([1,2,3,4,5],size=(4,4))
print(f)

[94 95 23 72 54 41 81 85 30 80]
[[688 468 291 634 231]
 [210   1 346  13 236]
 [826 314 395 307 359]]
[0.64666671 0.17236366 0.76872631 0.58498526 0.20206796]
[[0.58734846 0.84018957 0.6842744  0.98764989 0.26085225]
 [0.24653235 0.20145418 0.6607757  0.71996519 0.53160476]
 [0.95737643 0.20095879 0.3353369  0.86457033 0.3324869 ]]
3
[[1 4 3 4]
 [1 2 5 4]
 [4 1 3 5]
 [4 2 2 5]]


In [17]:
# Random data Distribution
# A random distribution is a set of random numbers that follow a certain probability density function.
x = r.choice([1,2,3,4,5],p=[0.1,0.2,0.3,0.4,0.0],size=(10)) #1-D array
print(x)
y = r.choice([1,2,3,4,5],p=[0.1,0.2,0.3,0.4,0.0],size=(3,5)) #2-D array
print(y)

[4 4 3 3 2 2 2 3 2 4]
[[3 2 4 4 2]
 [3 2 3 2 4]
 [4 3 4 4 4]]


Random Permutations of Elements

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation()

-->The shuffle() method makes changes to the original array.

-->The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [22]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Before Shuffling",x)
r.shuffle(x)
print("After Shuffling",x)
print("Permutation of x is:",r.permutation(x))

Before Shuffling [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Shuffling [[4 5 6]
 [7 8 9]
 [1 2 3]]
Permutation of x is: [[1 2 3]
 [7 8 9]
 [4 5 6]]
